config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books

  resources :authors

  resources :categories

  resource :order, only: [:show] do
  	put 'add/:book_id', to: 'orders#add', as: :add_to
  	put 'remove/:book_id', to: 'orders#remove', as: :remove_from
	end

  root to: 'books#index'

  devise_for :users,
  	:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_and_belongs_to_many :books

	validates :first_name, presence: true
	validates :last_name, presence: true

end

app/models/book.rb
class Book < ActiveRecord::Base

	has_and_belongs_to_many :authors
	has_and_belongs_to_many :categories
	has_one :book_cover, dependent: :destroy,  class_name: "Image::BookCover"

	validates :title, presence: true
	validates :price, presence: true
	validates :quantity, presence: true

	has_many :ratings
	has_many :customers, through: :ratings

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :books

	validates :name, presence: true, uniqueness: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :ratings
	has_many :books, through: :ratings

	validates :email, presence: true, uniqueness: true
	validates :first_name, presence: true
	validates :last_name, presence: true

end

app/models/image/book_cover.rb
module Image
	class BookCover < ActiveRecord::Base
		belongs_to :book

	  IMAGE_SIZES = {
	    :default => [900, 900],
	    :mini => [300, 900],
	    :thumb => [100, 300]
	  }

	  mount_uploader :image, ImageUploader

	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	include AASM

	belongs_to :user

	enum :state => [:in_progress, :in_queue, :in_delivery, :delivered]

	aasm :column => :state, :enum => true do
    state :in_progress, :initial => true
    state :in_queue
    state :in_delivery
    state :delivered
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
end

app/models/rating.rb
class Rating < ActiveRecord::Base

	belongs_to :book
	belongs_to :customer

	validates :review, presence: true
  enum rating_number: [:one, :two, :three, :four, :five, :six, :seven,
  											:eight, :nine, :ten]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

	def order_in_progress
    Order.find_or_initialize_by(:state=>Order.states[:in_progress])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user])
  end

  def default_url_options # /posts/new -> /posts/new?locale=en
    { locale: I18n.locale }
  end

  def set_current_user
    User.current_user = User.find_by_id(session[:user_id])
    yield
  ensure
    # to address the thread variable leak issues in Puma/Thin webserver
    User.current_user = nil
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @authors = Author.all
    respond_with(@authors)
  end

  def show
    respond_with(@author)
  end

  def new
    @author = Author.new
    respond_with(@author)
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    @author.save
    respond_with(@author)
  end

  def update
    @author.update(author_params)
    respond_with(@author)
  end

  def destroy
    @author.destroy
    respond_with(@author)
  end

  private
    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:first_name, :last_name, :description)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @books = Book.all
    respond_with(@books)
  end

  def show
    respond_with(@book)
  end

  def new
    @book = Book.new
    respond_with(@book)
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.save
    respond_with(@book)
  end

  def update
    @book.update(book_params)
    respond_with(@book)
  end

  def destroy
    @book.destroy
    respond_with(@book)
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :description, :price,
                                   :quantity)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < AplicationController

	before_action :authenticate_user!

	def add_item
		@order << item
	end
	helper_method :add_item

	def remove_item

	end

  private
	def current_user_order
		if current_user
			current_user.order_in_progress
		end
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/_form.html.haml
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing authors

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Description
      %th
      %th
      %th

  %tbody
    - @authors.each do |author|
      %tr
        %td= author.first_name
        %td= author.last_name
        %td= author.description
        %td= link_to 'Show', author
        %td= link_to 'Edit', edit_author_path(author)
        %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  %b First name,:
  = @author.first_name
%p
  %b Last name,:
  = @author.last_name
%p
  %b Description:
  = @author.description

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/books/_form.html.haml
= simple_form_for(@book) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :short_description
    = f.input :full_description
    = f.input :image
    = f.input :price

  .form-actions
    = f.button :submit

app/views/books/_list.html.haml
- @books.each do |book|
  %div[book]
    %ul.list-unstyled
      = Image::book_cover.book_id
      = link_to book.title, @book
      = book.price

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h3
  = t('pages.shop')
= render 'books/list'

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Full description:
  = @book.description
%p
  %b Price:
  = @book.price

= link_to 'Add to cart', :controller=>:orders, :action=>:add_item

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path